name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  tag-to-wordpress-org:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SLUG: bt-keyboard-shortcuts
          BUILD_DIR: bt-keyboard-shortcuts
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
